apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvv-smb
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: do-block-storage
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
      driver: "fstab/cifs"
      fsType: "cifs"
      secretRef:
        name: "cifs-secret"
      options:
        networkPath: "//54.92.215.187/juyel"
        mountOptions: "dir_mode=0755,file_mode=0644,noperm"
